# Generated by Django 5.1.6 on 2025-06-25 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbBuilding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone1', models.CharField(max_length=25)),
                ('phone2', models.CharField(blank=True, max_length=25, null=True)),
                ('phone3', models.CharField(blank=True, max_length=25, null=True)),
                ('email1', models.CharField(max_length=50)),
                ('email2', models.CharField(blank=True, max_length=50, null=True)),
                ('rep_name', models.CharField(blank=True, max_length=100, null=True)),
                ('rep_phone', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'building',
            },
        ),
        migrations.CreateModel(
            name='DbExpense',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('number_of_stops', models.IntegerField()),
                ('item', models.CharField(max_length=50)),
                ('unit', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('shaft', models.IntegerField()),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'expense',
            },
        ),
        migrations.CreateModel(
            name='DbOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'owner',
            },
        ),
        migrations.CreateModel(
            name='DbUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('usertype', models.IntegerField(choices=[(1, 'one'), (2, 'two')])),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='DbBuildingManager',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='TanaApp.dbbuilding')),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='DbBuildingStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('building_status', models.BooleanField()),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='TanaApp.dbbuilding')),
            ],
            options={
                'db_table': 'buildingstatus',
            },
        ),
        migrations.CreateModel(
            name='DbContract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(verbose_name='Starting Date')),
                ('end_date', models.DateTimeField()),
                ('paytime', models.IntegerField(verbose_name='Payment Duration (months)')),
                ('payed', models.IntegerField(choices=[(1, 'not payed'), (2, 'full pay'), (3, 'partial pay')], default=1)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='TanaApp.dbbuilding')),
            ],
            options={
                'db_table': 'contract',
            },
        ),
        migrations.CreateModel(
            name='DbDiscount',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.IntegerField()),
                ('discount_type', models.IntegerField(choices=[(1, 'contract time'), (2, 'discount by problem')])),
                ('discount_money', models.FloatField()),
                ('description', models.TextField()),
                ('description2', models.TextField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='TanaApp.dbcontract')),
            ],
            options={
                'db_table': 'discount',
            },
        ),
        migrations.CreateModel(
            name='DbElevator',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('commissionnumber', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('number_of_stops', models.IntegerField()),
                ('landing_door_unit', models.IntegerField()),
                ('landing_door_quantity', models.IntegerField()),
                ('drive_unit', models.IntegerField()),
                ('drive_quantity', models.IntegerField()),
                ('car', models.IntegerField()),
                ('car_quantity', models.IntegerField()),
                ('shaft_pit', models.IntegerField()),
                ('shaft_quantity', models.IntegerField()),
                ('Total', models.FloatField()),
                ('registerd_date', models.DateTimeField()),
                ('started_date', models.DateTimeField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevator_id', to='TanaApp.dbbuilding')),
            ],
            options={
                'db_table': 'elevator',
            },
        ),
        migrations.CreateModel(
            name='DBContractElevator',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractElevator', to='TanaApp.dbcontract')),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevatorC', to='TanaApp.dbelevator')),
            ],
            options={
                'db_table': 'contractElevator',
            },
        ),
        migrations.AddField(
            model_name='dbcontract',
            name='elevators',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='TanaApp.dbelevator'),
        ),
        migrations.CreateModel(
            name='DbExtra',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('money', models.FloatField()),
                ('discription', models.TextField()),
                ('discription1', models.TextField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='TanaApp.dbcontract')),
            ],
            options={
                'db_table': 'extra',
            },
        ),
        migrations.AddField(
            model_name='dbbuilding',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building', to='TanaApp.dbowner'),
        ),
        migrations.CreateModel(
            name='DBPartialPyment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('total', models.FloatField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial', to='TanaApp.dbcontract')),
            ],
            options={
                'db_table': 'partailpayment',
            },
        ),
        migrations.CreateModel(
            name='DbTimer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('expire', models.DateTimeField(auto_now_add=True)),
                ('payment_time', models.IntegerField()),
                ('payed', models.BooleanField(default=False)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TanaApp.dbbuilding')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TanaApp.dbdiscount')),
                ('elevator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TanaApp.dbelevator')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TanaApp.dbexpense')),
                ('extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TanaApp.dbextra')),
            ],
            options={
                'db_table': 'timer',
            },
        ),
        migrations.CreateModel(
            name='DbTotal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('is_Actiave', models.BooleanField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total', to='TanaApp.dbcontract')),
            ],
            options={
                'db_table': 'total',
            },
        ),
        migrations.CreateModel(
            name='DbMessage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='TanaApp.dbuser')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='DbWarranty',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='TanaApp.dbelevator')),
            ],
            options={
                'db_table': 'warranty',
            },
        ),
    ]
