# Generated by Django 5.1.6 on 2025-06-26 07:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TanaApp', '0002_delete_dbcontractelevator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('default_currency', models.CharField(max_length=3)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('default_timezone', models.CharField(default='UTC', max_length=50)),
                ('session_timeout', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('max_upload_size', models.PositiveIntegerField(default=10)),
                ('theme_color', models.CharField(default='#3b82f6', max_length=7)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('backup_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('smtp_server', models.CharField(blank=True, max_length=100)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('require_2fa', models.BooleanField(default=False)),
                ('password_expiry_days', models.PositiveIntegerField(default=90)),
                ('login_attempts_limit', models.PositiveIntegerField(default=5)),
                ('privacy_policy_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.CreateModel(
            name='PersonalizedSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('messages_enabled', models.BooleanField(default=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('dark_mode', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=False)),
                ('inbox_organization', models.CharField(choices=[('chrono', 'Chronological'), ('priority', 'Priority')], default='chrono', max_length=20)),
                ('auto_archive', models.BooleanField(default=False)),
                ('signature', models.TextField(blank=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('daily_summary_time', models.TimeField(default='09:00')),
                ('show_online_status', models.BooleanField(default=True)),
                ('keyboard_shortcuts', models.BooleanField(default=False)),
                ('font_size', models.PositiveIntegerField(default=14)),
                ('density', models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('comfort', 'Comfort')], default='normal', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personalized Settings',
            },
        ),
    ]
