# Generated by Django 5.1.6 on 2025-07-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TanaApp', '0004_alter_dbbuildingmanager_id_alter_dbbuildingstatus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbextra',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dbpartialpyment',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dbcontract',
            name='payed',
            field=models.IntegerField(choices=[(1, 'Not paid'), (2, 'Fully paid'), (3, 'Partial paid')], default=1),
        ),
    ]
