# Generated by Django 5.1.6 on 2025-07-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TanaApp', '0005_dbextra_time_dbpartialpyment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbdiscount',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dbpartialpyment',
            name='amount',
            field=models.FloatField(verbose_name='Amount paid (Not Total)'),
        ),
    ]
