# Generated by Django 5.1.6 on 2025-08-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TanaApp', '0006_alter_dbdiscount_time_alter_dbpartialpyment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbpartialpyment',
            name='total',
            field=models.FloatField(verbose_name='Total payment expected'),
        ),
    ]
