# Generated by Django 5.1.6 on 2025-08-20 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TanaApp', '0007_alter_dbpartialpyment_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbbuilding',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building', to='TanaApp.dbowner'),
        ),
    ]
