# Generated by Django 5.2.4 on 2026-01-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TanaApp', '0008_alter_dbbuilding_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbdiscount',
            name='carry',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
