# Generated by Django 5.2.4 on 2026-01-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TanaApp', '0009_dbdiscount_carry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbdiscount',
            name='carry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
