# Generated by Django 6.0.4 on 2026-05-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TanaApp', '0010_add_carry_field_to_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbdiscount',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dbextra',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
