# Generated by Django 6.0.4 on 2026-06-12 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TanaApp', '0011_dbdiscount_percentage_dbextra_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dbcontract',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DbContractScar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scars', to='TanaApp.dbcontract')),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_deletions', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_contract_deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contract_scar',
                'indexes': [models.Index(fields=['contract', 'deleted_at'], name='contract_sc_contrac_27cdfc_idx')],
            },
        ),
    ]
