# Generated by Django 6.0.4 on 2026-06-27 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TanaApp', '0012_dbcontract_deleted_at_dbcontractscar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalCorrectionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('manual', 'Manual / user action'), ('auto_audit', 'Background audit'), ('elevator_changed', 'Elevator created/updated/deleted'), ('contract_changed', 'Contract created/elevator attached'), ('extras_changed', 'Extra added/updated/deleted'), ('discounts_changed', 'Discount added/updated/deleted'), ('partial_changed', 'Partial payment added/updated/deleted')], default='manual', max_length=40)),
                ('previous_total', models.FloatField(blank=True, null=True)),
                ('new_total', models.FloatField()),
                ('delta', models.FloatField(default=0.0)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_logs', to='TanaApp.dbcontract')),
            ],
            options={
                'db_table': 'total_correction_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract', 'created_at'], name='total_corre_contrac_496bb6_idx'), models.Index(fields=['reason', 'created_at'], name='total_corre_reason_e10d7b_idx')],
            },
        ),
    ]
