# Generated by Django 6.0.6 on 2026-07-03 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TanaApp', '0013_totalcorrectionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbElevatorDiscount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('discount_money', models.FloatField(default=0.0)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description2', models.TextField(blank=True, default='')),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevator_discount', to='TanaApp.dbelevator')),
            ],
            options={
                'db_table': 'elevator_discount',
            },
        ),
        migrations.CreateModel(
            name='DbElevatorExtra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('money', models.FloatField(default=0.0)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('discription', models.TextField(blank=True, default='')),
                ('discription1', models.TextField(blank=True, default='')),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevator_extra', to='TanaApp.dbelevator')),
            ],
            options={
                'db_table': 'elevator_extra',
            },
        ),
    ]
