# Generated by Django 6.0.6 on 2026-07-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TanaApp', '0015_alter_personalizedsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='default_currency',
            field=models.CharField(blank=True, default='ETB', max_length=3),
        ),
    ]
